/* 8-BIT CPU EMULATOR IN PURE C _______
cpu takes machine code in program.bin 
generated by the assembler and executes it 

*/

#include "debug_cpu.h"
#include "control_unit.h" 

void initCPU(CPU*cpu) {
    if (SHOW_PC) COLOR_YELLOW; printf("\n=CYCLE==PC====OPCODE=======OPERANDS======="); COLOR_RESET;
    initCtrlUnit(cpu); // sets and inittializes default flags of cpu
    loadProgram(cpu); // loads machine code from external file and puts into rom
}
void runCPU(CPU*cpu) { // fetch decode and execute pipeline
    cpuFetch(cpu); // loads next instruction from rom into instruction register
    cpu->metrics.cycles++;    
    cpuDecodeExecute(cpu); 
    if (SHOW_PC) inspectPC(cpu);
}


int main(void) { 
    clock_t start = clock();
    CPU cpu = {0}; 
    
    initCPU(&cpu);
    while (cpu.isRunning && cpu.fatalError == NONE) {
        runCPU(&cpu);
    }

    clock_t end = clock();
    cpu.metrics.exetime = (double)(end - start) / CLOCKS_PER_SEC; // calculate execution time
    
    if (SHOW_RAM) inspectRam(&cpu);
    if (SHOW_REGISTERS) inspectRegisters(&cpu);
    if (SHOW_FLAGS) inspectFlags(&cpu);
    if (SHOW_METRICS) showMetrics(&cpu);
    if (SHOW_ERRORS) showFatalErrors(&cpu);
    
    return 0; 
}